# Generated by Django 5.0.2 on 2024-07-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the name of the author', max_length=100, verbose_name='Author Name')),
                ('last_name', models.CharField(help_text='Enter the surname of the author', max_length=100, verbose_name='Author Surname')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter the date of birth', null=True, verbose_name='Birthday')),
                ('about', models.TextField(help_text='Enter the data about author', verbose_name='About author')),
                ('photo', models.ImageField(blank=True, help_text='Upload author photo', null=True, upload_to='images', verbose_name='Author Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the genre of the book', max_length=200, verbose_name='Book Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the language of the book', max_length=20, verbose_name='Book Language')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the publisher of the book', max_length=20, verbose_name='Book Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the status of the book instance', max_length=20, verbose_name='Book Status')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=200, verbose_name='Book Title')),
                ('year', models.CharField(help_text='Enter the year of the book', max_length=4, verbose_name='Book Year')),
                ('summary', models.TextField(help_text='Enter the short summary of the book', max_length=1000, verbose_name='Book Annotation')),
                ('isbn', models.CharField(help_text='It must contain 13 symbols', max_length=13, verbose_name='ISBN of the Book')),
                ('photo', models.ImageField(help_text='Enter the cover of the book', upload_to='images', verbose_name='Book Cover')),
                ('author', models.ManyToManyField(help_text='Enter the author(s) of the book', to='catalog.author', verbose_name='Book Author(s)')),
                ('genre', models.ForeignKey(help_text='Enter the genre of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Book Genre')),
                ('language', models.ForeignKey(help_text='Enter the language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Book Language')),
                ('publisher', models.ForeignKey(help_text='Enter the publisher of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.publisher', verbose_name='Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(help_text='Enter the inventory number', max_length=20, null=True, verbose_name='Inventory Number')),
                ('due_back', models.DateField(blank=True, help_text='Enter the due date', null=True, verbose_name='Due date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change the status of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Status of the book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
