# Generated by Django 5.1 on 2024-08-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
    ]
